### PR TITLE
Updates for release of 1.0.2

### PR DESCRIPTION
**Pull request by aroc**
These are the required updates to release `v1.0.2`.

### CODE REVIEW

**Comment by dustinlarimer** [comment]
:+1:

**Comment by dustinlarimer** [comment]
Let's commit the built files too, since they get the `version` embedded directly: https://github.com/keen/keen-tracking.js/blob/master/dist/keen-tracking.js#L1324

**Comment by aroc** [comment]
Yeah good call!

**Comment by aroc** [comment]
Build files committed.

**Pull request merged**
