### PR TITLE
URI Encode the data attribute after we base64 encode it

### PR DESCRIPTION
**Pull request by josephwegner**
## What does this PR do? How does it affect users?
Special characters (like fancy unicode characters) create base64 strings with special characters in them. We need to encode those special characters, or else the Keen API gets mad.

## How should this be tested?

Send an event with an airplane in it! (JSONP only) 🛫

Things to keep in mind as you review:
 - Is URI Encoding ever a bad thing?

## Related tickets?

https://github.com/keen/keen-tracking.js/issues/53

### CODE REVIEW

**Comment by dustinlarimer** [comment]
@josephwegner would it be possible to get a test added to support this?

**Comment by dustinlarimer** [comment]
@josephwegner thanks for putting this together!

**Comment by aroc** [comment]
This has been added via #59. So I'm gonna close this.

**Comment by dustinlarimer** [comment]
Nice work, y'all! 👏 👏

**Pull request closed without merging**
