### PR TITLE
Drop properties with undefined values

### PR DESCRIPTION
**Pull request by aroc**
If a property value is undefined, it will throw an error in `clone` because you cannot `JSON.parse(JSON.stringify(undefined))`.

Instead, we just drop the property entirely here.

### CODE REVIEW

**Comment by aroc** [comment]
Back merged with master. CI should be running now.

**Comment by aroc** [comment]
Weird Circle failure. :/

**Comment by aroc** [comment]
Fixed!

**Comment by dustinlarimer** [comment]
:shipit:

**Pull request merged**
