### PR TITLE
v1.0.1 release

### PR DESCRIPTION
**Pull request by aroc**
Updates the `README.md` and `CHANGELOG.md` to include changes for `1.0.1` release.

### CODE REVIEW

**Comment by joannecheng** [comment]
Do you also need to update package.json?

**Comment by aroc** [comment]
I believe that gets updated as part of the `npm` tasks, no? Last time I updated the `package.json` myself, the `npm` task I ran *also* updated it and so it bumped it up a patch version number too high. But maybe there's a way to do NPM releases where it doesn't bump it?

**Comment by joannecheng** [comment]
Yes, you're right, I completely forgot that npm does that. :X

**Comment by dustinlarimer** [comment]
We've always manually updated the package version. NPM does have a command for this, but it's not required.

**Comment by dustinlarimer** [comment]
Also, this branch needs to be renamed and deleted, since `v1.0.1` needs to be the tag name and tags/branches collide like that : )

**Comment by aroc** [comment]
lol fun times! I'll rename and delete and updated package.json version.

**Pull request closed without merging**
