### PR TITLE
Respect client protocol

### PR DESCRIPTION
**Pull request by lukechilds**
Resolves https://github.com/keen/keen-tracking.js/issues/82

This gets me a [free shirt](https://blog.keen.io/hacktoberfest-2017-71e2c0d957c7) right?

### CODE REVIEW

**Comment by dustinlarimer** [comment]
@lukechilds nice work! 

Is there any way to put a test or two around this? I'm trying to think of a way to ensure it's operating properly, but we don't use mocking so I'm not sure how else to intercept the request. Any ideas there?

And yes, a t-shirt is certainly in order once this gets merged! 👍 👕

**Comment by lukechilds** [comment]
Yeah, I have an idea how to test, should have time tomorrow 👍

**Comment by dustinlarimer** [comment]
Awesome, thanks for your help! Excited to get this released :)

**Comment by dustinlarimer** [comment]
@lukechilds I also just fixed a bug in our tests – perhaps sync up with `master` when you get a chance so that doesn't cause issues 👍

**Comment by lukechilds** [comment]
Yeah, I noticed that, will do.

Also noticed it fails on the latest version of node, had to revert to v5 to get it to run. Want another PR for that?

**Comment by dustinlarimer** [comment]
Ah, yeah - looks like `process.EventEmitter` was dropped at some point along the way.. most likely used by a nested dependency of a dev dependency that needs updating. 

I'll open another issue for this. If you would like to tackle it, please go right ahead 😄

**Comment by dustinlarimer** [comment]
https://github.com/keen/keen-tracking.js/issues/95

**Comment by lukechilds** [comment]
Ok, I got the test working. I just intentionally give a hostname that doesn't exist so the request fails. Then check on the error if the port was 443 (HTTPS) or 80 (HTTP).

Kinda hacky, but it works `¯\_(ツ)_/¯`

**Comment by dustinlarimer** [comment]
Awesome - that certainly works.  Thanks for taking time to put that together 👍

**Comment by dustinlarimer** [comment]
@lukechilds you rock, thanks for these awesome PRs – shoot me an email at dustin@keen.io :)

**Pull request merged**
